# Generated by Django 2.0.5 on 2018-08-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('Porosity', models.CharField(max_length=100)),
                ('Permeability', models.CharField(max_length=100)),
                ('API', models.CharField(max_length=100)),
            ],
        ),
    ]
